# -*- coding: utf-8 -*-
"""cat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OqStoRYE6RhnbIQJqhtjZjJrNo85BCYo
"""

import cv2
from google.colab.patches import cv2_imshow

at = cv2.imread("/content/girl.jpeg") # 고양이 이미지 읽어오기
cv2_imshow(cat)

gray_cat = cv2.cvtColor(cat, cv2.COLOR_BGR2GRAY) # gray톤으로 바꾸기
# cv2_imshow( gray_cat)

hsv_cat = cv2.cvtColor(cat, cv2.COLOR_BGR2HSV) # hsv 으로 바꾸기

h, s, v = cv2.split(hsv_cat)
# cv2_imshow(h)
# cv2_imshow(s)
# cv2_imshow(v)

"""![색상표](https://i.stack.imgur.com/gyuw4.png)

빨강 0 ~ 5, 170 ~ 180 <br>
주황 5 ~ 25 <br>
노랑 25 ~ 35 <br>
연두 35 ~ 50 <br>
초록 50 ~ 70 <br>
하늘 70 ~ 95 <br>
파랑 95 ~ 115 <br>
남색 115 ~ 125 <br>
보라 125 ~ 140 <br>
연지 140 ~ 170 <br>
빨강 170 ~ 180, 0 ~ 5 <br>
"""

hsv_cat_colorlist = []
colorlist = [0,5,25,35,50,70,95,115,125,140,170,180]
colorlist2 = []
for i in range(len(colorlist)-1):
  colorlist2.append((colorlist[i] + colorlist[i+1])/2)
# print(colorlist2)

for i in range(len(colorlist)-1):
  hsv_cat_colorlist.append(hsv_cat.copy())
  hsv_cat_colorlist[i][:,:,0] = colorlist2[i]
  hsv_cat_colorlist[i] = cv2.cvtColor(hsv_cat_colorlist[i], cv2.COLOR_HSV2BGR)
  cv2_imshow(hsv_cat_colorlist[i])

i=3
maskfilter = cv2.inRange(h, colorlist[i], colorlist[i+1]) # 색깔 레인지 정해서 그부분만 255로 바꾸기
cat_maskfilter = cv2.bitwise_and(hsv_cat, hsv_cat, mask = maskfilter) # hsv 파일중에 255 인 부분만 남기기
cat_maskfilter = cv2.cvtColor(cat_maskfilter, cv2.COLOR_HSV2BGR) # hsv를 rgb로 바꾸기

cv2_imshow(cat_maskfilter)

# 색깔별로 같은 비중 확인 (픽셀수)
maskfilterlist = []
for i in range(len(colorlist)-1):
  maskfilter = cv2.inRange(h, colorlist[i], colorlist[i+1])
  maskfilterlist.append(maskfilter.sum()/255 +0.01*i)
print(maskfilterlist)

maskfilterlist[0] = maskfilterlist[0] + maskfilterlist[len(maskfilterlist)-1]
maskfilterlist.pop(len(maskfilterlist)-1) # 마지막 중복 빨강은 삭제
print(maskfilterlist)

maskfilterlist2 = maskfilterlist.copy()
maskfilterlist2.sort(reverse=True)
print(maskfilterlist)
print(maskfilterlist2)

color_ranklist = []
for i in range(len(colorlist)-2):
  color_ranklist.append(maskfilterlist.index(maskfilterlist2[i]))
print(color_ranklist) # 컬러 랭킹을 리스트에 담는다.

image_color = cv2.imread("/content/blue.jpg") # 색체 이미지 읽어오기
hsv_image_color = cv2.cvtColor(image_color, cv2.COLOR_BGR2HSV) # hsv 으로 바꾸기
hsv_image_color_h, hsv_image_color_s, hsv_image_color_v = cv2.split(hsv_image_color)

hsv_image_color_colorlist = []
# colorlist = [0,5,25,40,70,95,115,125,140,170,180]
colorlist2 = []
for i in range(len(colorlist)-1):
  colorlist2.append((colorlist[i] + colorlist[i+1])/2)
# print(colorlist2)

for i in range(len(colorlist)-1):
  hsv_image_color_colorlist.append(hsv_image_color.copy())
  hsv_image_color_colorlist[i][:,:,0] = colorlist2[i]
  hsv_image_color_colorlist[i] = cv2.cvtColor(hsv_image_color_colorlist[i], cv2.COLOR_HSV2BGR)
  
# 색깔별로 같은 비중 확인 (픽셀수)
image_color_maskfilterlist = []
for i in range(len(colorlist)-1):
  image_color_maskfilter = cv2.inRange(hsv_image_color_h, colorlist[i], colorlist[i+1])
  image_color_maskfilterlist.append(image_color_maskfilter.sum()/255 +0.01*i)

image_color_maskfilterlist[0] = image_color_maskfilterlist[0] + image_color_maskfilterlist[len(image_color_maskfilterlist)-1]
image_color_maskfilterlist.pop(len(image_color_maskfilterlist)-1) # 마지막 중복 빨강은 삭제


image_color_maskfilterlist2 = image_color_maskfilterlist.copy()
image_color_maskfilterlist2.sort(reverse=True)
print(image_color_maskfilterlist)
print(image_color_maskfilterlist2)

image_color_color_ranklist = []
for i in range(len(colorlist)-2):
  image_color_color_ranklist.append(image_color_maskfilterlist.index(image_color_maskfilterlist2[i]))
print(image_color_color_ranklist) # 컬러 랭킹을 리스트에 담는다.

h_new = h.copy() # 고양이에 새로 쓸 색상h 리스트 생성
h_new[:,:] = 0
h_new

for i in range(len(colorlist)-2):
# i = 0
  maskfilter = cv2.inRange(h, colorlist[color_ranklist[i]], colorlist[color_ranklist[i]+1]) # 색깔 레인지 정해서 그부분만 255로 바꾸기
  maskfilter = maskfilter/255*colorlist2[image_color_color_ranklist[i]]
  maskfilter
  h_new = h_new + maskfilter
  # h_new += maskfilter
print(h_new)

hsv_cat[:,:,0] = h_new.copy()
hsv_cat[:,:,0]

hsv_cat_new = cv2.cvtColor(hsv_cat, cv2.COLOR_HSV2BGR) # hsv를 rgb로 바꾸기

cv2_imshow(hsv_cat_new)

